### ISSUE TITLE
typescript compiler panic

### ISSUE THREAD

**Issue by faizhasim** [seek-oss/skuba#365]
This might be related to `skuba-dive` but I'm not entirely sure. The `tsc` child process panic and throw the following when I run `skuba format`. I tried to replicate by running `tsc --noEmit` and able to get same error:

```
/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:87004
                throw e;
                ^

TypeError: Cannot read property 'length' of undefined
    at getPropertyOfType (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:44084:45)
    at checkPropertyAccessExpressionOrQualifiedName (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:55755:24)
    at checkPropertyAccessExpression (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:55658:17)
    at checkExpressionWorker (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:60003:28)
    at checkExpression (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:59929:38)
    at maybeCheckExpression (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:59202:34)
    at checkBinaryExpression (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:59174:25)
    at checkExpressionWorker (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:60043:28)
    at checkExpression (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:59929:38)
    at checkParenthesizedExpression (/Users/faizhasim/dev/gh-seek/discover-acquisition-monorepo/node_modules/typescript/lib/tsc.js:59960:20)
```

I believe this is related to https://github.com/microsoft/TypeScript/issues/42350. I didn't debug enough to look for actual prob, but rather do the workaround by pinning typescript to v4.0.5. I tried to use latest typescript and the problem still occurs.

**Comment by 72636c** [comment]
Hiya @faizhasim, when are you getting this error? I don't have access to your Git repository and there's not much I can do without additional details on how to reproduce the error.

**Comment by faizhasim** [comment]
It's a new repo and we haven't push or commit anything yet. Context: we are trying to convert/re-compose existing code on skuba into a monorepo setup (yarn workspace). Changes is huge atm, I will try to replicate in smaller chunk.

**Comment by 72636c** [comment]
I'm aware that skuba (and sku for that matter) don't work particularly well with workspaces, but this crash seems rather dramatic. I'd be keen to understand more about your repository structure and how we can better support it with our tooling.

**Comment by faizhasim** [comment]
I will share later once we have more stable structure on this. For now, I found that changing tsconfig option to `allowJs: false` fix this. I would probably guess that this is related to typescript, not skuba.
